# https://github.com/grafana/loki/tree/main/production/helm/loki
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
serviceAccount:
  create: false
minio:
  enabled: true
loki:
  auth_enabled: false
  # type: filesystem
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
      enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: false
  ui:
    enabled: false

lokiCanary:
  enabled: true
resultsCache:
  enabled: false
chunksCache:
  enabled: false
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

# server:
#   http_listen_port: 3100
#   grpc_listen_port: 9096

# common:
#   instance_addr: 127.0.0.1
#   path_prefix: /tmp/loki
#   storage:
#     filesystem:
#       chunks_directory: /tmp/loki/chunks
#       rules_directory: /tmp/loki/rules
#   replication_factor: 1
#   ring:
#     kvstore:
#       store: inmemory

# query_range:
#   results_cache:
#     cache:
#       embedded_cache:
#         enabled: true
#         max_size_mb: 100

# schema_config:
#   configs:
#     - from: 2020-10-24
#       store: tsdb
#       object_store: filesystem
#       schema: v12
#       index:
#         prefix: index_
#         period: 24h
