apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db
  namespace: robco
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: robco
spec:
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: robotdb
        - name: POSTGRES_USER
          value: robotuser
        - name: POSTGRES_PASSWORD
          value: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db
      volumes:
      - name: postgres-db
        persistentVolumeClaim:
          claimName: postgres-db
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: robco
spec:
  type: ClusterIP # Access Scope: Internal to the cluster only. Exposes the service on a virtual IP inside the cluster.
  ports:
  - port: 5432
  selector:
    app: postgres-db
